_config.yml, _includes/registration.html, _includes/sponsors.html
=> Add new Rules

_includes/about.html
=> Remove the 'soon' thingy

_includes/registration.html
=> close registration form

_includes/header.html, _layouts/default.html, css/style.css, vendor/countdown_element.js
=> countdown - start event

vendor/countdown_element.js
=> countdown - finish event

_includes/header.html, _layouts/default.html
=> remove countdown

_includes/sponsors.html
just saw this on the live website :)
=> fix missing closing tag for sponsor email link

_layouts/default.html
This one removes Google Analytics. We should discuss if we want a replacement for this, though.
=> Tweak _layouts

_config.yml
Best viewed ignoring whitespace changes.
=> Tweak langs

_includes/about.html
This is a very minor details: competition v. contest. Contest one since it was more present.
=> For consistency

_config.yml, _includes/registration.html, _includes/sponsors.html
Sleepy me yesterday forgot to add a `_2020` and how English works.
=> Fix typos and 2020 edition

2018.html, 2019.html, 2020.html, _includes/registration.html
=> Updated form links and some wording

_includes/registration.html, css/style.css
- Change color and decoration of links in registration section so that they clearly stand out as links
=> Adjust registration-section-link class color and decoration

_config.yml, _includes/about.html, _includes/footer.html, _includes/header.html, _includes/judges.html, _includes/navigation.html, _includes/prizes.html, _includes/registration.html, _includes/rules.html, _includes/sponsors.html, _includes/winners.html, _layouts/default.html, css/style.css, winners.html
=> Fix some links

css/style.css
Let's see if this is it.
**Note**: don't do multiple CSS + HTML stuff at once lest we have to revert some.
=> Reverse previous hunk for UI improvements

_config.yml, _includes/footer.html, _includes/sponsor_logos.html, _includes/sponsors.html, css/style.css
Need approvals from all of you since this pertains the "us" (lowercase so it doesn't get confused with the country 😄).
=> Mention organizers

css/style.css
=> Fix not-so-mad-css-skills change

_config.yml, _includes/footer.html, css/style.css
(Brujo is sad that our current name is so humble)
Just throwing this out there.
🔥 and shuffle us around to (was sorted alphabetically, but "randomness" is better)
=> Name the team better

_includes/judges.html
=> Shuffle stuff around

_config.yml
Here lies some project ideas. Most of which were part of issue https://github.com/spawnfest/spawnfest.github.io/issues/123 . 
I don't feel like this is enough, but what is in the issue needs review, some have no definition yet. 
Closes #123.
=> Add new project ideas for 2021

_includes/header.html, css/style.css, vendor/countdown_element.js
As is tradition!
Don't need to merge this until Friday 11:59pm UTC
=> Put the count down widget in place

_includes/header.html, css/style.css
=> Add the coding is over banner

vendor/countdown_element.js
**Don't merge** until the competition starts (Saturday 15 Oct, at 0:01).
=> Prepare for "competition ends in 2 days" countdown display

_includes/about.html
I don't know when this got lost but "found" it today while going over the competition's history
=> Feature a blast from the past

_includes/about.html
Many times we aren't replying to anybody, just "regular"-tweeting...
=> Don't prevent @...-starting Tweets from being displayed

_includes/about.html
Maybe 500px was Ok at a given moment in time
=> Fix height

.gitignore, _config.yml, _includes/about.html, _includes/header.html, _includes/registration.html, _includes/sponsors.html
Accept (squash and merge this) only at Oct 17 00:01.
=> Prepare for evaluation time

2022.html, _config.yml, _includes/registration.html, css/style.css
Here they are, SpawnFest 2022's results 🎉 
Check https://spawnfest.org/2022.html out for more visually-appealing details.
=> 2022 winners 🥇🥈🥉 

_config.yml, _includes/header.html, js/countdown_element.js
Also tweaks some config. for semantics
=> Move countdown to "next 2 days"

_config.yml
This reverts commit 27525140fea442f65c5d142f6e7c8ddc36c9a732.
=> Revert "Make "competition is over" visible (#194)"

_config.yml
Sorry, karel_dreams; this slipped through the review cracks! :-(
=> Fix project description

_config.yml
=> Add winner user info
